[build]
  command = "export API_PREFIX=/.netlify/functions/ && export API_URL_BROWSER=$API_PREFIX && cd web/ && npm ci && npm run generate && cd ../server/ && npm ci && npm run build"
  functions = "server/dist/serverless"
  publish = "web/dist"
