platform: linux
image_resource:
  type: docker-image
  source: {repository: node}

inputs:
  - name: sources
    path: /src
  - name: npm-cache-source
    path: /cache

run:
  path: sh
  args:
    - -exc
    - |
      mv cache/node_modules src
      cd src && npm run build
