resource_types:
  - name: rsync-resource
    type: docker-image
    source:
      repository: mrsixw/concourse-rsync-resource
      tag: latest

  - name: telegram-notification
    type: docker-image
    source:
      repository: w32blaster/concourse-telegram-notifier
      tag: latest

  - name: concourse-ssh-resource
    type: docker-image
    source:
      repository: edtan1/concourse-ssh-resource
      tag: latest

resources:
  - name: repository
    type: git
    source:
      uri: https://github.com/spluseins/spluseins.git
      branch: master

  - name: server-deploy-dev
    type: rsync-resource
    source:
      server: spluseins.de
      base_dir: /home/concourse/build-result-dev
      user: concourse
      disable_version_path: true
      private_key: {{server-key}}

  - name: server-deploy-prod
    type: rsync-resource
    source:
      server: spluseins.de
      base_dir: /home/concourse/build-result-prod
      user: concourse
      disable_version_path: true
      private_key: {{server-key}}

  - name: telegram-notification
    type: telegram-notification
    source:
      bot_token: {{telegram-bot-token}}

  - name: restart-pm2
    type: concourse-ssh-resource
    source:
      hostname: spluseins.de
      username: concourse
      private_key: {{server-key}}

jobs:

  - name: build-dev
    serial: true
    plan:
      - get: repository
        trigger: true

      - task: install-dependencies
        file: repository/concourse/install.yml

      - task: insert-information
        file: repository/concourse/insert-information.yml
        params: {
                 "TEAM_MEMBER1": Mitglied-1,
                 "TEAM_MEMBER2": Mitglied-2,
                 "TEAM_MEMBER3": Mitglied-3,
                 "TEAM_MEMBER4": Mitglied-4
                }

      - task: build-frontend
        file: repository/concourse/build-frontend.yml
        params: {"API_URL": "https://master.spluseins.de/"}

      - task: build-api
        file: repository/concourse/build-api.yml

      - task: run-tests
        file: repository/concourse/tests.yml

      - put: server-deploy-dev
        params: {"sync_dir" : "build-result",
                 "rsync_opts" : ["--delete-after", "--recursive"]}
             
      - put: restart-pm2
        params:
          command: pm2 restart all

    on_success:
      do:
      - put: telegram-notification
        params:
          chat_id: {{telegram-chat-id}}
          text: "DEV #$BUILD_NAME: Build und Deployment waren erfolgreich! [Report](https://ci.spluseins.de/teams/main/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME)"
   
    on_failure:
      do:
      - put: telegram-notification
        params: 
          chat_id: {{telegram-chat-id}}
          text: "DEV #$BUILD_NAME: Build und Deployment sind fehlgeschlagen! [Report](https://ci.spluseins.de/teams/main/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME)"

    on_abort:
      do:
      - put: telegram-notification
        params: 
          chat_id: {{telegram-chat-id}}
          text: "DEV #$BUILD_NAME: Build und Deployment wurden abgebrochen! [Report](https://ci.spluseins.de/teams/main/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME)"
                 
  - name: build-prod
    serial: true
    plan:
      - get: repository
        passed: [build-dev]

      - task: install-dependencies
        file: repository/concourse/install.yml

      - task: insert-information
        file: repository/concourse/insert-information.yml
        params: {
                 "TEAM_MEMBER1": {{team-member1}},
                 "TEAM_MEMBER2": {{team-member2}},
                 "TEAM_MEMBER3": {{team-member3}},
                 "TEAM_MEMBER4": {{team-member4}}
                }

      - task: build-frontend
        file: repository/concourse/build-frontend.yml
        params: {"API_URL": "https://spluseins.de/"}

      - task: build-api
        file: repository/concourse/build-api.yml
      
      - put: server-deploy-prod
        params: {"sync_dir" : "build-result",
                 "rsync_opts" : ["--delete-after", "--recursive"]}
                 
      - put: restart-pm2
        params:
          command: pm2 restart all

    on_success:
      do:
      - put: telegram-notification
        params:
          chat_id: {{telegram-chat-id}}
          text: "PROD #$BUILD_NAME: Build und Deployment waren erfolgreich! [Report](https://ci.spluseins.de/teams/main/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME)"
    
    on_failure:
      do:
      - put: telegram-notification
        params: 
          chat_id: {{telegram-chat-id}}
          text: "PROD #$BUILD_NAME: Build und Deployment sind fehlgeschlagen! [Report](https://ci.spluseins.de/teams/main/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME)"
    
    on_abort:
      do:
      - put: telegram-notification
        params: 
          chat_id: {{telegram-chat-id}}
          text: "PROD #$BUILD_NAME: Build und Deployment wurden abgebrochen! [Report](https://ci.spluseins.de/teams/main/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME)"