resource_types:
- name: rsync-resource
  type: docker-image
  source: {repository: mrsixw/concourse-rsync-resource}

regit-repo:
  - name: git-repo
    type: git
    source:
      uri: https://github.com/spluseins/spluseins.git
      branch: cli-setup
  - name: server-deploy
    type: rsync-resource
    source:
      server: spluseins.de
      base_dir: /home/build-results
      user: concourse
      disable_version_path: true
      private_key: {{server-key}}

jobs:
- name: nuxt-build
  plan:
    - get: git-repo
      trigger: true

    - task: install-and-build
      file: git-repo/concourse/build.yml

    - put: server-deploy
      params: {"sync_dir": "build-result"}

