resource_types:
  - name: rsync-resource
    type: docker-image
    source: {repository: mrsixw/concourse-rsync-resource}

resources:
  - name: repository
    type: git
    source:
      uri: https://github.com/spluseins/spluseins.git
      branch: cli-setup

  - name: server-deploy
    type: rsync-resource
    source:
      server: spluseins.de
      base_dir: /home/concourse
      user: concourse
      disable_version_path: true
      private_key: {{server-key}}

jobs:
  - name: nuxt-build
    plan:
      - get: repository
        trigger: true

      - task: install-and-build
        file: repository/concourse/build.yml

      - put: server-deploy
