resource_types:
- name: rsync-resource
  type: docker-image
  source: {repository: mrsixw/concourse-rsync-resource}

- name: server-deploy
  type: rsync-resource
  source:
    server: spluseins.de
    base_dir: /home/build-results
    user: concourse
    disable_version_path: true
    private_key: {{server-key}}

resources:
  - name: sources
    type: git
    source:
      uri: https://github.com/spluseins/spluseins.git
      branch: cli-setup

jobs:
- name: build
  plan:
    - get: sources
      trigger: true

    - task: build
      file: sources/concourse/build.yml

    - put: server-deploy
      params: {"sync_dir": "build-result"}

