name: "Server Build"

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
  pull_request:
  merge_group:

defaults:
  run:
    working-directory: ./server

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version-file: "server/.nvmrc"
      - run: npm ci
      - run: npm run lint
      - run: npm run fmt:check
      - run: npm run build
      - run: npm run test
        env:
          CI: true
