name: Dev Deploy

# Allow the staging builds to be triggered manually
on: workflow_dispatch

# Define common variables for all jobs since all use the dokku action
env:
  REMOTE_HOST: "ssh://dokku@spluseins-i.ostfalia.de:8080"

concurrency: deploy-dev

jobs:
  deploy-web-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
        with:
          fetch-depth: 0
      - name: Deploy with dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: "${{ env.REMOTE_HOST }}/web-staging"
          ssh_private_key: ${{ secrets.PRIVATE_KEY }}
          git_push_flags: "--force"
  deploy-api-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
        with:
          fetch-depth: 0
      - name: Deploy with dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: "${{ env.REMOTE_HOST }}/api-staging"
          ssh_private_key: ${{ secrets.PRIVATE_KEY }}
          git_push_flags: "--force"
