name: Dev Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [dev]
    workflow_dispatch:

# Define common variables for all jobs since all use the dokku action
env:
  REMOTE_HOST: "ssh://dokku@spluseins-i.ostfalia.de:8080"

jobs:
  cancel-prev:
    runs-on: ubuntu-latest
    steps:
      # third-party action that cancels previous runs
      - uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
  deploy-web-staging:
    runs-on: ubuntu-latest
    needs: cancel-prev
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Deploy with dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: "${{ env.REMOTE_HOST }}/web-staging"
          ssh_private_key: ${{ secrets.PRIVATE_KEY }}
          git_push_flags: "--force"
  # deploy-api-staging:
  #   runs-on: ubuntu-latest
  #   needs: cancel-prev
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0
  #     - name: Deploy with dokku
  #       uses: dokku/github-action@master
  #       with:
  #         git_remote_url: "${{ env.REMOTE_HOST }}/api-staging"
  #         ssh_private_key: ${{ secrets.PRIVATE_KEY }}
  #         git_push_flags: "--force"
